### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by meleu** [meleu/rpie-art#1]
- [x] install overlays for arcade games.
- [x] install generic overlays for any system
- [x] install overlays for any game/system (not only the arcade ones)
- [x] uninstall overlays/launching art
- [x] improve the ROM searching (look in gamelist.xml, etc)
- [x] install generic launching images for any system
- [x] install game specific launching image (any system)
- [x] `*_image` entries in the `info.txt` file can be a URL (only http[s] supported).
- [x] add an updating feature to the script.
- [x] use of `creator` entry.
- [ ] install scrape images
- [x] add support for clones (`rom_clones` in info.txt)
- [ ] improve feedback to the user while downloading files/cloning repositories (use `dialog --gauge`).

**Comment by UDb23** [comment]
My priority from next week will be provide high quality "Scrape Images" for all overlays in the repo.
This means you may be soon get a request for that box missing a tick up there in your todo list ;-)

**Comment by meleu** [comment]
I have a date to restart the work here: 19-July-2017. Until then I'll be a little busy.

But I think I'll solve that. I worked out my xml editing skills when writing that tool for @Used2BeRX. :-)

**Comment by UDb23** [comment]
Thanks! 
No rush intended.  :-)
